/* WhatsApp Chat Widget — generated by {{ config('config.site_name', 'Platform') }} */
(function () {
    'use strict';

    var cfg = {
        phone:       '{{ $phone }}',
        color:       '{{ addslashes($cfg['color']) }}',
        position:    '{{ addslashes($cfg['position']) }}',
        buttonText:  '{{ addslashes($cfg['button_text']) }}',
        prefill:     '{{ addslashes($cfg['prefill']) }}',
        showTooltip: {{ $cfg['show_tooltip'] ? 'true' : 'false' }},
        tooltipText: '{{ addslashes($cfg['tooltip_text']) }}'
    };

    function inject() {
        // --- CSS ---
        var style = document.createElement('style');
        style.textContent = [
            '#wa-widget-btn{position:fixed;z-index:9999;display:flex;align-items:center;gap:10px;',
            'border-radius:50px;padding:12px 20px;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.2);',
            'border:none;color:#fff;font-family:inherit;font-size:14px;font-weight:600;',
            'transition:transform .2s,box-shadow .2s;background:' + cfg.color + ';}',
            '#wa-widget-btn:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,.25);}',
            '#wa-widget-btn svg{flex-shrink:0;}',
            '#wa-widget-tooltip{position:fixed;z-index:9998;background:#fff;color:#333;',
            'border-radius:8px;padding:8px 14px;font-size:13px;box-shadow:0 4px 12px rgba(0,0,0,.15);',
            'white-space:nowrap;pointer-events:none;transition:opacity .3s;}',
        ].join('');
        document.head.appendChild(style);

        // --- Button ---
        var btn = document.createElement('button');
        btn.id = 'wa-widget-btn';

        var isRight = cfg.position === 'bottom-right';
        btn.style.cssText = 'bottom:24px;' + (isRight ? 'right:24px;' : 'left:24px;');

        btn.innerHTML = [
            '<svg width="22" height="22" viewBox="0 0 32 32" fill="currentColor">',
            '<path d="M16 3C8.82 3 3 8.82 3 16c0 2.28.61 4.52 1.76 6.49L3 29l6.72-1.74A13 13 0 0 0 16 29c7.18 0 13-5.82 13-13S23.18 3 16 3zm6.45 18.55c-.27.76-1.58 1.46-2.17 1.5-.55.04-1.08.27-3.63-.75-3.05-1.22-5-4.33-5.15-4.53-.15-.2-1.22-1.62-1.22-3.1s.77-2.2 1.04-2.5c.27-.3.6-.37.8-.37.2 0 .4.01.57.01.19 0 .44-.07.69.52.27.62.9 2.2.98 2.36.08.16.13.35.03.56-.1.2-.15.33-.3.5-.15.17-.31.38-.44.51-.15.15-.3.3-.13.6.17.3.76 1.25 1.63 2.02 1.12.99 2.06 1.3 2.36 1.44.3.15.47.12.64-.07.17-.2.74-.86.94-1.15.2-.3.4-.24.67-.14.27.1 1.73.82 2.03.97.3.15.5.22.57.34.07.12.07.7-.2 1.47z"/>',
            '</svg>',
            '<span>' + cfg.buttonText + '</span>',
        ].join('');

        btn.addEventListener('click', function () {
            var url = 'https://wa.me/' + cfg.phone;
            if (cfg.prefill) url += '?text=' + encodeURIComponent(cfg.prefill);
            window.open(url, '_blank', 'noopener,noreferrer');
        });

        document.body.appendChild(btn);

        // --- Tooltip ---
        if (cfg.showTooltip && cfg.tooltipText) {
            var tip = document.createElement('div');
            tip.id = 'wa-widget-tooltip';
            tip.textContent = cfg.tooltipText;
            tip.style.cssText = 'bottom:80px;opacity:0;' + (isRight ? 'right:24px;' : 'left:24px;');
            document.body.appendChild(tip);

            setTimeout(function () { tip.style.opacity = '1'; }, 1200);
            btn.addEventListener('mouseenter', function () { tip.style.opacity = '1'; });
            btn.addEventListener('mouseleave', function () { tip.style.opacity = '0'; });
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', inject);
    } else {
        inject();
    }
})();
